kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2
metadata:
  name: djangohpa
  namespace: django
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    name: django
    kind: Deployment
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
