kind: Deployment
apiVersion: apps/v1
metadata:
  name: nginx
  namespace: django
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:                     # ✅ Add this block
      labels:
        app: nginx
    spec:
      containers:
      - name: nginximage
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-configmap
